### ISSUE TITLE
Gradel issue

### ISSUE THREAD

**Issue by rayalatrinadh** [Mina-Mikhail/Kotlin-Base-MVVM#2]
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found
![Screenshot (23)](https://user-images.githubusercontent.com/31477828/136506442-a223ee5d-38bc-45fb-b5ea-0207c4b91652.png)
.

**Comment by Mina-Mikhail** [comment]
Fixed
